esHombre(salvador).
esHombre(jesus).
esHombre(manuel).
esHombre(jesusC).
esHombre(salvadorC).
esHombre(antonioC).
esHombre(luisC).
esHombre(enrique).
esHombre(antonioM).
esHombre(alberto).
esHombre(isaias).
esHombre(ramon).
esHombre(jose).
esHombre(brandon).
esHombre(jesusH).
esHombre(julian).
esHombre(eduardo).
esHombre(alessandro).
esHombre(luisH).
esHombre(joseH).
esHombre(jesusM).
esHombre(aaron).
esHombre(noe).
esHombre(edgar).
esHombre(juan).
esHombre(hector).
esHombre(axel).
esHombre(angel).
esHombre(pablo).
esHombre(carlos).
esHombre(gael).
esHombre(alejandro).

esMujer(elba).
esMujer(hermelinda).
esMujer(arcelia).
esMujer(sugey).
esMujer(adriana).
esMujer(betty).
esMujer(norma).
esMujer(myrna).
esMujer(ana).
esMujer(concepcion).
esMujer(hilda).
esMujer(gloria).
esMujer(maria).
esMujer(sandra).
esMujer(guadalupe).
esMujer(sophia).
esMujer(breanna).
esMujer(imperia).
esMujer(sarai).
esMujer(ivette).
esMujer(leslie).
esMujer(barbara).
esMujer(ximena).
esMujer(berenice).
esMujer(ambar).
esMujer(yaretzi).
esMujer(loreto).
esMujer(citlali).
esMujer(liliana).
esMujer(diane).
esMujer(elizabeth).
esMujer(maritza).
esMujer(lorena).
esMujer(yamilet).
esMujer(camila).
esMujer(michell).
esMujer(alexa).
esMujer(hanna).

papa(salvador,manuel).
papa(salvador,jesusC).
papa(salvador,salvadorC).
papa(salvador,betty).
papa(salvador,luisC).
papa(jesus,norma).
papa(jesus,enrique).
papa(jesus,ana).
papa(jesus,antonioM).
papa(jesus,hilda).
papa(jesus,isaias).
papa(jesus,maria).
papa(jesus,jose).
papa(manuel,sandra).
papa(manuel,guadalupe).
papa(manuel,brandon).
papa(manuel,sophia).
papa(jesusC,jesusH).
papa(jesusC,imperia).
papa(jesusC,sarai).
papa(salvadorC,julian).
papa(salvadorC,ivette).
papa(salvadorC,leslie).
papa(antonioC,alessandro).
papa(antonioC,barbara).
papa(antonioC,ximena).
papa(luisC,berenice).
papa(luisC,luisH).
papa(enrique,ambar).
papa(enrique,yaretzi).
papa(antonioM,joseH).
papa(antonioM,loreto).
papa(antonioM,jesusM).
papa(alberto,aaron).
papa(alberto,citlali).
papa(alberto,liliana).
papa(isaias,noe).
papa(isaias,elizabeth).
papa(ramon,maritza).
papa(ramon,hector).
papa(jesusH,yamilet).
papa(eduardo,camila).
papa(noe,axel).
papa(noe,michell).
papa(edgar,alexa).
papa(edgar,angel).
papa(juan,pablo).
papa(juan,carlos).
papa(juan,gael).
papa(hector,alejandro).
papa(hector,hanna).

mama(elba,manuel).
mama(elba,jesusC).
mama(elba,salvadorC).
mama(elba,betty).
mama(elba,luisC).
mama(hermelinda,norma).
mama(hermelinda,enrique).
mama(hermelinda,ana).
mama(hermelinda,antonioM).
mama(hermelinda,hilda).
mama(hermelinda,isaias).
mama(hermelinda,maria).
mama(hermelinda,jose).
mama(arcelia,sandra).
mama(arcelia,guadalupe).
mama(arcelia,brandon).
mama(arcelia,sophia).
mama(sugey,jesusH).
mama(sugey,imperia).
mama(sugey,sarai).
mama(adriana,julian).
mama(adriana,ivette).
mama(adriana,leslie).
mama(betty,alessandro).
mama(betty,barbara).
mama(betty,ximena).
mama(norma,berenice).
mama(norma,luisH).
mama(myrna,ambar).
mama(myrna,yaretzi).
mama(concepcion,joseH).
mama(concepcion,loreto).
mama(concepcion,jesusM).
mama(hilda,aaron).
mama(hilda,citlali).
mama(hilda,liliana).
mama(gloria,noe).
mama(gloria,elizabeth).
mama(maria,maritza).
mama(maria,hector).
mama(breanna,yamilet).
mama(leslie,camila).
mama(diane,axel).
mama(diane,michell).
mama(elizabeth,alexa).
mama(elizabeth,angel).
mama(maritza,pablo).
mama(maritza,carlos).
mama(maritza,gael).
mama(lorena,alejandro).
mama(lorena,hanna).

esposos(salvador,elba).
esposos(elba,salvador).
esposos(hermelinda,jesus).
esposos(jesus,hermelinda).
esposos(manuel,arcelia).
esposos(arcelia,manuel).
esposos(jesusC,sugey).
esposos(sugey,jesusC).
esposos(salvadorC,adriana).
esposos(adriana,salvadorC).
esposos(betty,antonioC).
esposos(antonioC,betty).
esposos(luisC,norma).
esposos(norma,luisC).
esposos(enrique,myrna).
esposos(myrna,enrique).
esposos(antonioM,concepcion).
esposos(concepcion,antonioM).
esposos(isaias,gloria).
esposos(gloria,isaias).
esposos(maria,ramon).
esposos(ramon,maria).
esposos(jesusH,breanna).
esposos(breanna,jesusH).
esposos(leslie,eduardo).
esposos(eduardo,leslie).
esposos(noe,diane).
esposos(diane,noe).
esposos(elizabeth,edgar).
esposos(edgar,elizabeth).
esposos(maritza,juan).
esposos(juan,maritza).
esposos(hector,lorena).
esposos(lorena,hector).


hijos(Y,X):-papa(X,Y);mama(X,Y).
hijo(Y,X):-esHombre(Y),hijos(Y,X).
hija(Y,X):-esMujer(Y),hijos(Y,X).
hermanos(X,Y):- ((papa(Z,X),papa(Z,Y));(mama(Z,X),mama(Z,Y))),X\=Y.
hermano(X,Y):- esHombre(X),hermanos(X,Y).
hermana(X,Y):- esMujer(X),hermanos(X,Y).
abuelo(X,Y):-(papa(Z,Y);mama(Z,Y)),papa(X,Z).
abuela(X,Y):-(papa(Z,Y);mama(Z,Y)),mama(X,Z).
abuelos(X,Y):-abuelo(X,Y);abuela(X,Y).
abuelosPaterno(X,Y):-papa(Z,Y),(papa(X,Z);mama(X,Z)).
abuelosMaterno(X,Y):-mama(Z,Y),(papa(X,Z);mama(X,Z)).
abueloP(X,Y):-papa(Z,Y),papa(X,Z).
abueloM(X,Y):-mama(Z,Y),papa(X,Z).
abuelaP(X,Y):-papa(Z,Y),mama(X,Z).
abuelaM(X,Y):-mama(Z,Y),mama(X,Z).
nietos(X,Y):-abuelos(Y,X).
nieto(X,Y):-esHombre(X),nietos(X,Y).
nieta(X,Y):-esMujer(X),nietos(X,Y).
tios(X,Y):-hijos(Y,Z),hermanos(Z,X).
tio(X,Y):-esHombre(X),tios(X,Y).
tia(X,Y):-esMujer(X),tios(X,Y).
sobrinos(X,Y):-hijos(X,Z),hermanos(Z,Y).
sobrino(X,Y):-esHombre(X),sobrinos(X,Y).
sobrina(X,Y):-esMujer(X),sobrinos(X,Y).
primos(X,Y):-(papa(Z,X);mama(Z,X)),(papa(W,Y);mama(W,Y)),hermanos(Z,W).
primo(X,Y):-esHombre(X),primos(X,Y).
prima(X,Y):-esMujer(X),primos(X,Y).

padre(X,Y):-papa(X,Y);mama(X,Y).
ascend(Asc,Desc):-padre(Asc,Desc).
ascend(Asc,Desc):-padre(Asc,Hijo),ascend(Hijo,Desc).

primosP(X,Y):- esposos(X,Z),primos(Z,Y).
suegro(X,Y):- esposos(Y,Z),papa(X,Z).
suegra(X,Y):- esposos(Y,Z),mama(X,Z).
suegros(X,Y):-suegro(X,Y);suegra(X,Y).
cuñados(X,Y):-esposos(X,Z),hermanos(Z,Y).
tiosP(X,Y):-esposos(X,Z),tios(Z,Y).
yerno(X,Y):-esHombre(X),esposos(X,Z),(papa(Y,Z);mama(Y,Z)).


